name: Tag and Publish Go Binaries

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name (e.g., v1.2.3)"
        required: true
        type: string

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23"

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o ryskV12-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o ryskV12-linux-arm64
          GOOS=darwin GOARCH=arm64 go build -o ryskV12-darwin-arm64

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.tag_name }}
          draft: false
          prerelease: false

      - name: Upload Linux amd64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ryskV12-linux-amd64
          asset_name: ryskV12-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Linux arm64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ryskV12-linux-arm64
          asset_name: ryskV12-linux-arm64
          asset_content_type: application/octet-stream
          
      - name: Upload Darwin arm64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ryskV12-darwin-arm64
          asset_name: ryskV12-darwin-arm64
          asset_content_type: application/octet-stream