name: Tag and Publish Go Binaries

on:
  push:
    tags:
      - "*" # Trigger on any tag

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23"

      - name: Get tag name
        id: tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o ryskV12-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o ryskV12-linux-arm64

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
          release_name: Release ${{ steps.tag_name.outputs.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload Linux amd64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ryskV12-linux-amd64
          asset_name: ryskV12-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Linux arm64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ryskV12-linux-arm64
          asset_name: ryskV12-linux-arm64
          asset_content_type: application/octet-stream
